- name: Ponicode Unit Test
  # You may pin to the exact commit or the version.
  # uses: ponicode/unit-testing-action@ab61a5a8e527affa366dda30d40fb205147b2513
  uses: ponicode/unit-testing-action@0.0.1-christmas
  with:
    # Path of repo to generate unit tests for
    repoPath: # default is ./
    # Ponicode token to use Ponicode API
    authToken: # default is 
    # Boolean. Enter true to generate test for changes since last repo or enter false if you want to generate for the whole repo
    changedFilesOnly: # optional, default is false
    # String. Enter the path to your coverage-final.json (Example: coverage/coverage-final.json)
    coverageJsonPath: # optional
